### PR TITLE
Create Gluster volume api

### PR DESCRIPTION
**Pull request by anupnivargi**

### CODE REVIEW

**Comment by r0h4n** [comment]
@brainfunked Please review, ruby code

**Comment by r0h4n** [comment]
@anupnivargi Please add travis job and also tests for this patch

**Comment by mkudlej** [comment]
Hi,
I've checkouted this patch and try it on CentOS 7. Here are my notes:

1. There is not Ruby 2.3.1 on CentOS 7 but 2.0.0. **Please consider to support Ruby 2.0.0**
2. Because of 1. I've commented done these changes in Gemfile:
 
```
-ruby '2.3.1'
+ruby '2.0.0'
```

and 

```
-gem 'activesupport', require: false
+#gem 'activesupport', require: false
```

3. I've seen this after API server start:

```
bundle exec shotgun -Ilib
== Shotgun/Puma on http://127.0.0.1:9393/
Puma starting in single mode...
* Version 3.4.0 (ruby 2.0.0-p598), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:9393
Use Ctrl-C to stop
```

but any request(for example http://127.0.0.1:9393/1.0) outputs this:

```
                                              Boot Error

   Something went wrong while loading config.ru

  LoadError: cannot load such file -- active_support/core_ext/hash

 /root/work/anuptednrl/app.rb:6:in `require'
 /root/work/anuptednrl/app.rb:6:in `<top (required)>'
 config.ru:1:in `require'
 config.ru:1:in `block in inner_app'
 /usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
 /usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
 config.ru:1:in `new'
 config.ru:1:in `inner_app'
 /usr/local/share/gems/gems/shotgun-0.9.2/lib/shotgun/loader.rb:113:in `eval'
 /usr/local/share/gems/gems/shotgun-0.9.2/lib/shotgun/loader.rb:113:in `inner_app'
 /usr/local/share/gems/gems/shotgun-0.9.2/lib/shotgun/loader.rb:103:in `assemble_app'
 /usr/local/share/gems/gems/shotgun-0.9.2/lib/shotgun/loader.rb:86:in `proceed_as_child'
 /usr/local/share/gems/gems/shotgun-0.9.2/lib/shotgun/loader.rb:31:in `call!'                       
 /usr/local/share/gems/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'                        
 /usr/local/share/gems/gems/shotgun-0.9.2/lib/shotgun/favicon.rb:12:in `call'                       
 /usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'                     
 /usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'                              
 /usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'                              
 /usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'                            
 /usr/local/share/gems/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'                      
 /usr/local/share/gems/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
 /usr/local/share/gems/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
 /usr/local/share/gems/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
 /usr/local/share/gems/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `call'
 /usr/local/share/gems/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

**Comment by anivargi** [comment]
@mkudlej I will add support for ruby 2.0. 

You receive the error since you commented out the activesupport gem, I am guessing you have issues installing the gem since you downgraded to ruby 2.0

**Comment by anupnivargi** [comment]
Closing the PR, created a new one at https://github.com/Tendrl/tendrl/pull/7

**Pull request closed without merging**
